### PR TITLE
ENH: compatability with NLsolve.jl 0.14.0+

### PR DESCRIPTION
**Pull request by sglyon**
These are pretty minor changes to be compatible with NLsolve.jl versions >= 0.14.0

In the transition from 0.13.x to 0.14.0 nlsolve made a few breaking changes. 

@albop  I'll probably merge and tag a new release tomorrow, but will leave open until then to give you a chance to review

cc @jlperla

### CODE REVIEW

**Comment by jlperla** [comment]
Thanks to you both.  Can you tell me when the tag reaches metadata (or teach me how to automatically get automatically notified of a package being updated in the repository, so I don't need to bug you guy!

After it gets up there, I will take care of testing in on juliabox.  In the meantime, I will keep trying to harass juliabox crew to add to an image.

**Comment by sglyon** [comment]
Tag merged!

https://github.com/JuliaLang/METADATA.jl/pull/13119

**Comment by jlperla** [comment]
Awesome. Does that mean a Pkg.add gets the right version?

**Comment by sglyon** [comment]
After Pkg.update so metadata knows about dolo 0.3.1.

**Comment by albop** [comment]
Thank you @sglyon

**Pull request merged**
