### PR TITLE
Concrete types for each interpolation flavor

### PR DESCRIPTION
**Pull request by sglyon**

### CODE REVIEW

**Comment by albop** [comment]
Thanks @sglyon . One consequence of moving to `Point{d}` and `ListOfPoint{d}` is that we are no longer compatible with AxisArrays (as input to decision rules).
Indeed, the d.r. can't take AbstractArray as input anymore, as the memory layout of input is no longer indifferent. 
This is easy to fix, but I confess I hadn't paid that much attention to it.

**Comment by albop** [comment]
I guess the best way to fix that is to replace all the calls `reintepret(Point{d}, s', (N,))` (which is very error prone if the `'` is forgotten) by a wrapper which makes a copy of s' when required.

**Comment by sglyon** [comment]
Ahh that's right. Looks like the tests are failing there. I like your idea of the helper method to convert from matrix to list of points. It would be too easy to forget the transpose somewhere...

**Comment by albop** [comment]
I reviewed the code and it seems OK, so I will merge without further delay. Thanks for adding the tests of decision rules.
Fixing this AxisArrays was useful as it made me realize there are many places where we use array views, which will need some changes.

**Pull request merged**
