### PR TITLE
Azh/product gdp

### PR DESCRIPTION
**Pull request by AnasZa**
Adding a functions to discretize the product of  processes as GDP:
```
var=Dolo.VAR1(rho,Sigma)
var2=Dolo.VAR1(rho1,Sigma1)

pp=Dolo.ProductProcess(var,var2)

Dolo.discretize(Dolo.DiscretizedProcess,pp)
```
`Dolo.discretize(pp)` returns however `MarkovDiscretizedProcess`.

### CODE REVIEW

**Comment by albop** [comment]
Thank you @AnasZa !
Apparently the new function `discretize(...)` is defined too early in the file `processes.jl` (Travis says ProductProcess not defined). You could move it to the end of the file, just after `discretize(::Type{DiscreteMarkovProcess}, pp::ProductProcess;)`. 
Actually, you can copy the definition of this method to pass arguments to the subprocesses.

**Comment by albop** [comment]
As for the `ProductGrid` function, I suggest:

**Comment by albop** [comment]
Also I suggest:
- to rename `ProductGrid` as `Product`, since the argument type made it clear what it does
- in the function `Product(gdp_1, gdp_2)`  you can remove the checks. If the grids are not of the right type, the ProductGrid inside will complain.

**Comment by AnasZa** [comment]
Ok. But what about the fact that by default it is discretized as MC rather then GDP as in simple case?

**Comment by albop** [comment]
It's fine. There has to be a default, right ? MC is a good one.

**Comment by albop** [comment]
It seems to work. But there is no test for the new functionality. Could you add one ?

**Pull request merged**
