### PR TITLE
ENH: replace evaluate function with methods for call

### PR DESCRIPTION
**Pull request by sglyon**
This Pr replaces the `evaluate` function with new methods for `Base.call`. So now instead of `evaluate(dr, args...)` we do `dr(args...)`

### CODE REVIEW

**Comment by albop** [comment]
@sglyon : Any reason to not do it ?

**Comment by sglyon** [comment]
nope.

Performance is the same, syntax is cleaner. No hesitation from me

**Comment by albop** [comment]
OK then. Merging now.

**Comment by sglyon** [comment]
Sounds good to me, did you mean to merge or close?

**Comment by albop** [comment]
I clicked on both... Let me try again

**Pull request merged**
