### PR TITLE
Sl/perfect foresight updates

### PR DESCRIPTION
**Pull request by sglyon**
Hey @albop  and @jperla, I have uploaded a Dolo.jl version of the RMT3 chapter 11 computations we did with dolo.py a few years ago.

In order to make them work I had to extend a bit the functionality of Dolo.jl

This PR has all that you need to run the (included) notebook.

@albop a quick review+tag would be great as this would then be ready to go

### CODE REVIEW

**Comment by albop** [comment]
Thanks @sglyon . The linter picked up an error with the yaml file:
```
julia> Dolo.lint("examples/models/rmt3_ch11.yaml")
error at line 43, column 4 : Invalid calibration 'tau_c' >> tau_c already declared in calibration section at line 39, column 4
error at line 44, column 4 : Invalid calibration 'tau_k' >> tau_k already declared in calibration section at line 40, column 4
```
I just made the trivial correction on your branch

**Comment by sglyon** [comment]
Thank you!

The linter is great. That’s actually the first time I’ve seen it in action (crazy, I know)

**Comment by albop** [comment]
No problem. I appeared during last summer and this proves it is useful :
kudos to @ezgioz !

**Comment by sglyon** [comment]
Are you ok if I merge and tag a patch release?

**Comment by albop** [comment]
Yes, please go ahead. I'm now having a look at the notebook but that shouldn't stop us

**Comment by albop** [comment]
From a quick look it looks good to me. There is a small typo at the end of the `transition` equation (`m_tt`) and I wish there was something better than `vcat(fill(0.0, 9), 0.2)`...
Also, you made an implementation of plot_irfs. It is good where it is: we probably don't want a dependency on PyPlot in the main codebase.

**Comment by sglyon** [comment]
Thanks, I'll fix the transition equation and then merge.

I could also do `[fill(0.0, 9); 0.2]` instead of the version that calls `vcat`.

**Comment by albop** [comment]
Cool! So there is no equivalent to python [0.0]*9 ? <curiosity mode off>

**Comment by sglyon** [comment]
Nope, you need to call `fill` or `repeat`. 

I guess to make myself feel better about that I would say that you can't create a numpy array  with [0.0]*9 either as bumpy interprets the `*` like Julia does.

**Comment by albop** [comment]
I'm just suprised there isn't a hidden operator that does it.

**Pull request merged**
